# Generated by Django 5.2.4 on 2025-07-13 08:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='intro_en',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='intro_fr',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='intro_uk',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
