# Generated by Django 5.2.4 on 2025-07-13 08:37

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogindexpage_intro_en_blogindexpage_intro_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='body_en',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body_fr',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body_uk',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='date_en',
            field=models.DateField(null=True, verbose_name='Post date'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='date_fr',
            field=models.DateField(null=True, verbose_name='Post date'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='date_uk',
            field=models.DateField(null=True, verbose_name='Post date'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='intro_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='intro_fr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='intro_uk',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
