# Generated by Django 5.2.4 on 2025-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogtagindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtagindexpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogtagindexpage',
            name='intro_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogtagindexpage',
            name='intro_fr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogtagindexpage',
            name='intro_uk',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
