# Generated by Django 5.2.4 on 2025-07-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_hero_cta_homepage_hero_cta_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body_fr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body_uk',
        ),
    ]
