# Generated by Django 5.2.4 on 2025-07-14 10:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpage',
            name='body',
            field=wagtail.fields.StreamField([('card', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('caption', 0), ('notice', 0), ('text', 1), ('image', 2)]], {'group': 'Cards'})}, help_text='Use this section to list your projects and skills.'),
        ),
        migrations.AddField(
            model_name='cardpage',
            name='body_en',
            field=wagtail.fields.StreamField([('card', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('caption', 0), ('notice', 0), ('text', 1), ('image', 2)]], {'group': 'Cards'})}, help_text='Use this section to list your projects and skills.', null=True),
        ),
        migrations.AddField(
            model_name='cardpage',
            name='body_fr',
            field=wagtail.fields.StreamField([('card', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('caption', 0), ('notice', 0), ('text', 1), ('image', 2)]], {'group': 'Cards'})}, help_text='Use this section to list your projects and skills.', null=True),
        ),
        migrations.AddField(
            model_name='cardpage',
            name='body_uk',
            field=wagtail.fields.StreamField([('card', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('caption', 0), ('notice', 0), ('text', 1), ('image', 2)]], {'group': 'Cards'})}, help_text='Use this section to list your projects and skills.', null=True),
        ),
    ]
