# Generated by Django 5.2.4 on 2025-07-14 10:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_cardpage_body_alter_cardpage_body_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpage',
            name='body',
            field=wagtail.fields.StreamField([('card', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.StructBlock', [[('notice', 0), ('amount', 0)]], {'required': False}), 2: ('wagtail.blocks.StreamBlock', [[('price', 1)]], {'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('price', 2), ('notice', 0), ('text', 3), ('image', 4)]], {'group': 'Cards'})}, help_text='Use this section to list your projects and skills.'),
        ),
        migrations.AlterField(
            model_name='cardpage',
            name='body_en',
            field=wagtail.fields.StreamField([('card', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.StructBlock', [[('notice', 0), ('amount', 0)]], {'required': False}), 2: ('wagtail.blocks.StreamBlock', [[('price', 1)]], {'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('price', 2), ('notice', 0), ('text', 3), ('image', 4)]], {'group': 'Cards'})}, help_text='Use this section to list your projects and skills.', null=True),
        ),
        migrations.AlterField(
            model_name='cardpage',
            name='body_fr',
            field=wagtail.fields.StreamField([('card', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.StructBlock', [[('notice', 0), ('amount', 0)]], {'required': False}), 2: ('wagtail.blocks.StreamBlock', [[('price', 1)]], {'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('price', 2), ('notice', 0), ('text', 3), ('image', 4)]], {'group': 'Cards'})}, help_text='Use this section to list your projects and skills.', null=True),
        ),
        migrations.AlterField(
            model_name='cardpage',
            name='body_uk',
            field=wagtail.fields.StreamField([('card', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.StructBlock', [[('notice', 0), ('amount', 0)]], {'required': False}), 2: ('wagtail.blocks.StreamBlock', [[('price', 1)]], {'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('price', 2), ('notice', 0), ('text', 3), ('image', 4)]], {'group': 'Cards'})}, help_text='Use this section to list your projects and skills.', null=True),
        ),
    ]
