# Generated by Django 5.2.4 on 2025-07-14 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_alter_cardpage_body_alter_cardpage_body_en_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Cardpage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
