# -*- coding: utf-8 -*-
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

import environ
from django.utils.translation import gettext_lazy as _

# Environ instance
env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SOURCE_DIR = BASE_DIR / "src"

# read environ
READ_DOT_ENV_FILE = env.bool("DJANGO_READ_DOT_ENV_FILE", default=True)
ENV_PATH = env.str("DJANGO_ENV_PATH", default=".env")
if READ_DOT_ENV_FILE:
    environ.Env.read_env(os.path.join(BASE_DIR, ENV_PATH))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["*"])
CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[])
CORS_ALLOWED_ORIGINS = env.list("DJANGO_ALLOWED_CORS", default=[])
APPEND_SLASH = True

# Application definition
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
]

WAGTAIL_TRANSLATION_APPS = [
    "wagtail_modeltranslation",
    "wagtail_modeltranslation.makemigrations",
    "wagtail_modeltranslation.migrate",
]

WAGTAIL_APPS = [
    "wagtail.contrib.forms",
    "wagtail.contrib.settings",
    "wagtail.contrib.redirects",
    "wagtail.contrib.frontend_cache",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail.users",
    "wagtail",
    "modelcluster",
    "taggit",
]

LOCAL_APPS = [
    "src.core",
    "src.blog",
    "src.portfolio",
    "src.home",
    "src.card",
]
THIRD_PARTY_APPS = [
    "debug_toolbar",
    "django_components",
    "django_vite",
]

INSTALLED_APPS = (
    DJANGO_APPS
    + WAGTAIL_TRANSLATION_APPS
    + LOCAL_APPS
    + WAGTAIL_APPS
    + THIRD_PARTY_APPS
)

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    # "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "django_components.middleware.ComponentDependencyMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            "components",
        ],
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "src.core.context_processors.site_context",
                "wagtail.contrib.settings.context_processors.settings",
            ],
            "loaders": [
                "django.template.loaders.filesystem.Loader",
                "django.template.loaders.app_directories.Loader",
                "django_components.template_loader.Loader",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("POSTGRES_HOST"),
        "PORT": env("POSTGRES_PORT"),
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# AUTH_USER_MODEL = "users.User"
LANGUAGE_CODE = "en"

WAGTAIL_CONTENT_LANGUAGES = LANGUAGES = [
    ("en", _("English")),
    ("uk", _("Ukrainian")),
    ("fr", _("French")),
]
WAGTAILADMIN_PERMITTED_LANGUAGES = [
    # ("ru", _("Russian")),
    # ("en", _("English")),
    ("uk", _("Ukrainian")),
]

TIME_ZONE = "Europe/Kyiv"

USE_I18N = True

USE_TZ = True

# The path from which the translation for the pages is obtained
LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]

# Django vite settings
# ------------------------------------------------------------------------------
DJANGO_VITE_ASSETS_PATH = BASE_DIR / "static_nodejs"
DJANGO_VITE_STATIC_URL_PREFIX = "nodejs"
DJANGO_VITE_DEV_MODE = env.bool("DJANGO_VITE_DEV_MODE", default=True)
DJANGO_VITE_DEV_SERVER_HOST = env.str("DJANGO_VITE_DEV_SERVER_HOST")
DJANGO_VITE_DEV_SERVER_PORT = 3000
DJANGO_VITE_MANIFEST_PATH = DJANGO_VITE_ASSETS_PATH / "nodejs/manifest.json"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, "collect_static")
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "components",
    BASE_DIR / "static",
    DJANGO_VITE_ASSETS_PATH,
]

# Django components render
COMPONENTS = {
    "template_cache_size": 100,
    "libraries": [],
    "dirs": [],
}

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "django_components.finders.ComponentsFileSystemFinder",
]

# Media files
# https://docs.djangoproject.com/en/5.0/topics/files/
MEDIA_URL = env.str("MEDIA_URL", default="/media/")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# JWT settings
# ------------------------------------------------------------------------------
ACCESS_EXPIRATION = env.int("ACCESS_EXPIRATION", default=3)
REFRESH_EXPIRATION = env.int("REFRESH_EXPIRATION", default=3)
JWT_SECRET_KEY = env.str("JWT_SECRET_KEY")
JWT_ALGORITHM = env.str("JWT_ALGORITHM", default="HS256")

# Debug toolbar panels settings
# ------------------------------------------------------------------------------
DEBUG_TOOLBAR_PANELS = [
    "debug_toolbar.panels.versions.VersionsPanel",
    "debug_toolbar.panels.timer.TimerPanel",
    "debug_toolbar.panels.settings.SettingsPanel",
    "debug_toolbar.panels.headers.HeadersPanel",
    "debug_toolbar.panels.request.RequestPanel",
    "debug_toolbar.panels.sql.SQLPanel",
    "debug_toolbar.panels.staticfiles.StaticFilesPanel",
    "debug_toolbar.panels.templates.TemplatesPanel",
    "debug_toolbar.panels.cache.CachePanel",
    "debug_toolbar.panels.signals.SignalsPanel",
    "debug_toolbar.panels.logging.LoggingPanel",
    "debug_toolbar.panels.redirects.RedirectsPanel",
]

INTERNAL_IPS = env.list("DJANGO_INTERNAL_IPS", default="127.0.0.1")
# Logging
# ------------------------------------------------------------------------------
# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "formatters": {
#         "verbose": {
#             "format": "{levelname}: {asctime} - {message}",
#             "style": "{",
#         },
#         "simple": {
#             "format": "{levelname} {message}",
#             "style": "{",
#         },
#     },
#     "handlers": {
#         "console": {
#             "level": "INFO",
#             "class": "logging.StreamHandler",
#             "formatter": "verbose",
#         },
#         "telegram": {
#             "level": "ERROR",
#             "class": "src.core.utils.telegram_handler.TelegramHandler",
#         },
#     },
#     "root": {
#         "handlers": ["console"],
#         "level": "INFO",
#     },
#     "loggers": {
#         "django": {
#             "level": "INFO",
#             "handlers": ["console", "telegram"],
#             "propagate": False,
#         },
#     },
# }
# Server host
# -----------------------------------------------------------------------------
SERVER_HOST = env.str("SERVER_HOST", default="http:/127.0.0.1/")
# Telegram loging settings
# ------------------------------------------------------------------------------
TELEGRAM_BOT_TOKEN = env.str("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = env.str("TELEGRAM_CHAT_ID")
TELEGRAM_LOGGING_ENABLED = env.bool("TELEGRAM_LOGGING_ENABLED", default=False)

# Wagtail settings
# ------------------------------------------------------------------------------
WAGTAIL_SITE_NAME = "Energy"

WAGTAILADMIN_BASE_URL = env.str(
    "DJANGO_WAGTAILADMIN_BASE_URL", default="http://127.0.0.1:8000/admin/"
)  # noqa

WAGTAILIMAGES_EXTENSIONS = ["gif", "jpg", "jpeg", "png", "webp", "svg"]  # noqa
WAGTAIL_WORKFLOW_ENABLED = False
WAGTAILMODELTRANSLATION_TRANSLATE_SLUGS = False  # noqa
WAGTAIL_ALLOW_UNICODE_SLUGS = False
WAGTAIL_ENABLE_UPDATE_CHECK = False

DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000

WAGTAILADMIN_RICH_TEXT_EDITORS = {
    "default": {
        "WIDGET": "wagtail.admin.rich_text.DraftailRichTextArea",
        # since sub, super, and a couple more are not included by default, we need to add them in this config
        "OPTIONS": {
            "features": [
                "bold",
                "italic",
                "superscript",
                "subscript",
                "h1",
                "h2",
                "h3",
                "h4",
                "h5",
                "h6",
                "ol",
                "ul",
                "hr",
                "blockquote",
                "link",
                "embed",
                "document-link",
                "image",
            ],
        },
    },
    "minimal": {
        "OPTIONS": {
            "features": ["bold", "italic", "subscript", "superscript", "link"],
        },
    },
}

# Super user credentials
# ------------------------------------------------------------------------------
ADMIN_EMAIL = env.str("ADMIN_EMAIL", default="admin@admin.com")
ADMIN_USERNAME = env.str("ADMIN_USERNAME", default="admin")
ADMIN_PASSWORD = env.str("ADMIN_PASSWORD", default="Zaqwerty123@")

# User credentials
# ------------------------------------------------------------------------------
USER_EMAIL = env.str("USER_EMAIL", default="user@user.com")
USER_PASSWORD = env.str("USER_PASSWORD", default="Zaqwerty123@")

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

WAGTAIL_AGING_PAGES_ENABLED = False
