# Generated by Django 5.2.4 on 2025-07-13 14:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_formpage_formfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='intro_en',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='intro_fr',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='intro_uk',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
